# -*- coding: utf-8 -*-
"""Construction_Project_Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8Nw1cQRp7m1bQEPb08rgNhjSwhEw_58
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/construction_dataset.csv')
print(df.shape)
print(df.head())

# Risk Level wise Cost Analysis
risk_analysis = df.groupby('Risk_Level').agg(
    Total_Tasks=('Task_ID', 'count'),
    Avg_Cost=('Material_Cost_USD', 'mean'),
    Total_Cost=('Material_Cost_USD', 'sum'),
    Avg_Delay=('Start_Constraint', 'mean')
).round(2)

print(risk_analysis)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Construction Project Cost & Performance Analytics',
             fontsize=16, fontweight='bold')

# Chart 1 - Risk vs Total Cost
colors = ['#E74C3C', '#3498DB', '#2ECC71']
axes[0,0].barh(risk_analysis.index, risk_analysis['Total_Cost'], color=colors)
axes[0,0].set_title('Total Cost by Risk Level')
axes[0,0].set_xlabel('Total Cost (USD)')

# Chart 2 - Pie Chart
axes[0,1].pie(risk_analysis['Total_Cost'], labels=risk_analysis.index,
              autopct='%1.1f%%', colors=colors)
axes[0,1].set_title('Cost Distribution by Risk Level')

# Chart 3 - Avg Delay
axes[1,0].bar(risk_analysis.index, risk_analysis['Avg_Delay'], color=colors)
axes[1,0].set_title('Average Delay by Risk Level')
axes[1,0].set_ylabel('Days')

# Chart 4 - Task Count
axes[1,1].bar(risk_analysis.index, risk_analysis['Total_Tasks'], color=colors)
axes[1,1].set_title('Total Tasks by Risk Level')
axes[1,1].set_ylabel('Count')

plt.tight_layout()
plt.savefig('construction_analytics.png', dpi=150)
plt.show()

# Key Insights Report
print("=" * 50)
print("  CONSTRUCTION PROJECT ANALYTICS REPORT")
print("=" * 50)

print(f"\n📊 DATASET OVERVIEW")
print(f"   Total Tasks: {len(df)}")
print(f"   Total Cost: ${df['Material_Cost_USD'].sum():,.2f}")
print(f"   Avg Delay: {df['Start_Constraint'].mean():.2f} days")

print(f"\n⚠️ RISK ANALYSIS")
for risk in ['Low', 'Medium', 'High']:
    data = df[df['Risk_Level'] == risk]
    print(f"\n   {risk} Risk:")
    print(f"   - Tasks: {len(data)}")
    print(f"   - Total Cost: ${data['Material_Cost_USD'].sum():,.2f}")
    print(f"   - Avg Delay: {data['Start_Constraint'].mean():.2f} days")

print(f"\n💡 KEY INSIGHTS")
print(f"   1. Low risk tasks = 51% of total cost")
print(f"   2. High risk tasks have highest avg delay ({df[df['Risk_Level']=='High']['Start_Constraint'].mean():.2f} days)")
print(f"   3. 1300 total tasks analyzed")
print(f"   4. Total project cost = $64.38M")

print("\n" + "=" * 50)
print("  Report by: Adil Zafar | Data Analyst")
print("=" * 50)